### ISSUE TITLE
回调地址有没有办法不用https？

### ISSUE THREAD

**Issue by aricyu** [xiaoyaojian/OwinOAuthProvider#3]
有没有通过配置的方式使用http而不是https？

**Comment by xiaoyaojian** [comment]
貌似Sina和tencent不允许回调地址是http

**Comment by aricyu** [comment]
我fork了代码，把前缀改进了OPtion里。
然后我用http，目前没发现问题。。

**Comment by xiaoyaojian** [comment]
好，其实问题还是出在option上，最近没时间改
